apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: voting-dapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template: 
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend 
        image: votingdapprt3cc.azurecr.io/backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000 
        env:
        # Environment variables db url and jwt key from github secrets
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: backend-secret
                key: DATABASE_URL
    
          - name: JWT_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: backend-secret
                key: JWT_SECRET_KEY