apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: voting-dapp
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer