apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: voting-dapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template: # Pod template (blueprint for creating pods)
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432 # mapp the target port in the service
        env:
        # Environment variables for PostgreSQL from github secrets
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres
              key: POSTGRES_DB
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-storage
      volumes:
      - name: postgres-storage
        emptyDir: {}  # For testing
