FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Expose the port
EXPOSE 5000

# Set environment variables
ENV FLASK_APP=run.py
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_ENV=development
#TODO change it to a file(still not working)
#RUN ls -l /app

# Move migration commands to entrypoint script
#RUN chmod +x entrypoint.sh

# Run the entrypoint script at container startup
#CMD ["./entrypoint.sh"]


RUN echo '#!/bin/sh\n\
echo "Waiting for database..."\n\
sleep 5\n\
echo "Setting up database..."\n\
flask db init || true\n\
flask db migrate || true\n\
flask db upgrade\n\
echo "Starting application..."\n\
flask run\n' > /app/entrypoint.sh && chmod +x /app/entrypoint.sh

# Run the entrypoint script at container startup
CMD ["/app/entrypoint.sh"]