apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: voting-dapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template: 
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: votingdapprt3cc.azurecr.io/frontend:latest
        ports:
        - containerPort: 3000 
      