name: CD Pipeline

on:
    workflow_dispatch:
    push:
        branches: [ "main" ]
        paths:
            - 'k8s/**'
            - '.github/workflows/deploy.yml'

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: acr_creds

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Log in to Azure Container Registry
              uses: azure/docker-login@v2
              with:
                login-server: votingdapprt3cc.azurecr.io
                username: ${{ secrets.ACR_USERNAME }}
                password: ${{ secrets.ACR_PASSWORD }}
            - name: Verify Docker login
              run: docker info
              
            - name: Build frontend image
              run: |
                docker build -t votingdapprt3cc.azurecr.io/frontend:latest ./frontend
                docker push votingdapprt3cc.azurecr.io/frontend:latest
                

