name: CD Pipeline

on:
    workflow_dispatch:
    push:
        branches: [ "main" ]
        paths:
            - 'k8s/**'
            - '.github/workflows/deploy.yml'

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: acr_creds

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Azure CLI login
              run: az login -u ${{ secrets.AZURE_USERNAME }} -p ${{ secrets.AZURE_PASSWORD }}

            - name: Get AKS credentials
              run: az aks get-credentials --resource-group my-voting-dapp-rg --name voting-dapp-aks --overwrite-existing
            
            - name: Show current context
              run: kubectl config current-context

            - name: Log in to Azure Container Registry
              uses: azure/docker-login@v2
              with:
                login-server: votingdapprt3cc.azurecr.io
                username: ${{ secrets.ACR_USERNAME }}
                password: ${{ secrets.ACR_PASSWORD }}

            - name: Verify Docker login
              run: docker info

            - name: Build and push frontend image to acr 
              run: |
                docker build -t votingdapprt3cc.azurecr.io/frontend:latest ./frontend
                docker push votingdapprt3cc.azurecr.io/frontend:latest
            
            - name: Build and push backend image to acr 
              run: |
                docker build -t votingdapprt3cc.azurecr.io/backend:latest ./backend
                docker push votingdapprt3cc.azurecr.io/backend:latest

            - name: Create namespace
              run: |
                kubectl create namespace voting-dapp || echo "Namespace 'voting-dapp' already exists"
            
            - name: Create db secret
              run: |
                kubectl create secret generic postgres-secret -n voting-dapp  \
                --from-literal=POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
                --from-literal=POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
                --from-literal=POSTGRES_DB=${{ secrets.POSTGRES_DB }} \
                --dry-run=client -o yaml | kubectl apply -f -

            - name : Create backend secret
              run: |
                kubectl create secret generic backend-secret -n voting-dapp \
                --from-literal=DATABASE_URL=${{ secrets.DATABASE_URL }} \
                --from-literal=JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} \
                --dry-run=client -o yaml | kubectl apply -f -
            
            - name: Deploy frontend
              run: |
                kubectl apply -f k8s/frontend/frontend-deployment.yaml
                kubectl apply -f k8s/frontend/frontend-service.yaml

            - name: Deploy PostgreSQL
              run: |
                kubectl apply -f k8s/database/db-deployment.yaml
                kubectl apply -f k8s/database/db-service.yaml
            
            - name: Deploy backend
              run: |
                kubectl apply -f k8s/backend/backend-deployment.yaml
                kubectl apply -f k8s/backend/backend-service.yaml
            

                