name: CD Pipeline

on:
    workflow_dispatch:
    push:
        branches: [ "main" ]
        paths:
            - 'k8s/**'
            - '.github/workflows/deploy.yml'

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Log in to Azure Container Registry
              uses: azure/docker-login@v1
              with:
                login-server: <your_acr>.azurecr.io
                username: ${{ secrets.ACR_USERNAME }}
                password: ${{ secrets.ACR_PASSWORD }}
            - name: Verify Docker login
              run: |
                docker info
                docker logout <your_acr>.azurecr.io

