# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Frontend CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths: 
      - 'frontend/**'
  pull_request:
    branches: [ "main" ]
    paths: 
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        
    - name: Install dependencies
      run: |
        cd frontend
        npm ci
        
    - name: Build app
      run: |
        cd frontend
        CI=false npm run build   
  test: 
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        
    - name: Install dependencies
      run: |
        cd frontend
        npm ci

    - name: Run CandidatesPage tests
      run: |
        cd frontend
        CI=true npm test CandidatesPage.test.js --watchAll=false  
